### PR TITLE
PY3 str are now accepted when containing non ascii characters.

### PR DESCRIPTION
**Pull request by trollfot**

### CODE REVIEW

**Comment by jugmac00** [comment]
Some comments only, no review, as I do not know this library:

- this would fix #15 
- additionally, a change log entry would be nice

**Comment by icemac** [comment]
Any news on this PR?

**Comment by icemac** [comment]
Hm, now the tests are failing on Python 2.7. I think this is because now `zope.interface >= 5` is used. Maybe this can be fixed like in `zope.site`: https://github.com/zopefoundation/zope.site/pull/13/files#diff-24738dc36cfaa62a280b22dab72f2eab

**Comment by mgedmin** [comment]
> Hm, now the tests are failing on Python 2.7. I think this is because now zope.interface >= 5 is used. Maybe this can be fixed like in zope.site: https://github.com/zopefoundation/zope.site/pull/13/files#diff-24738dc36cfaa62a280b22dab72f2eab

I bet git master fails with the same problem, now that zope.interface made `iface.__module__`  readonly.  We need to fix this, but not necessarily as part of this PR.

**Comment by mgedmin** [comment]
> We need to fix this, but not necessarily as part of this PR.

https://github.com/zopefoundation/martian/pull/18

**Comment by icemac** [comment]
So let's wait until #18 is merged and can be used here.

**Pull request merged**
